apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: bqmlymgua-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/bqmlymgua-dotnet-basic-gitops